version: "3"

services:
  house-talker-nextjs:
    container_name: house-talker-nextjs-container
    image: house-talker-nextjs-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4100:3000
    env_file:
      - .env
